name: Warm Pipedream Reactivate

on:
  schedule:
    - cron: "*/5 * * * *"   # elke 5 minuten
  workflow_dispatch:         # handmatig starten

jobs:
  ping-pipedream-reactivate:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Pipedream Reactivate
        run: curl -s -o /dev/null "${{ secrets.PING_REACTIVATE_URL }}"
